### ISSUE TITLE
Elastic Search Controller

### ISSUE THREAD

**Issue by kgmills** [CMPUT301F16T05/legendary-telegram#10]
This one...

Needs to be able to post Requests to the server, then take the ID the server gives said request and tell the other classes to assign said ID to that request. 

Needs to be able to search by location, retrieve by location. 

And probably many other things that we'll learn of along the way.

**Comment by Cryosaurus** [comment]
Being able to communicate with the server is central to core functionality of other tasks, marking as priority

**Comment by Cryosaurus** [comment]
Tweaks can still be done but this has been done for a long time.
