### ISSUE TITLE
User - Email field of user profile is only accepting numeric characters

### ISSUE THREAD

**Issue by Cryosaurus** [CMPUT301F16T05/legendary-telegram#27]
I was testing to see if I could get to the rider/driver view and noticed when I tried to create a new user that  the email field was only showing number. Letters and special characters were all being turned to numbers as well.

**Comment by kgmills** [comment]
I will fix this and push asap.

**Comment by kgmills** [comment]
This was fixed by swapping the email and phone fields. Convent since a phone number should only be numbers.
