### ISSUE TITLE
Do we need store a Rider instance in the Request?

### ISSUE THREAD

**Issue by ZhimaoLin** [CMPUT301F16T05/legendary-telegram#3]
I know the requirement does not require that driver should be able to see the contact information of rider. However, I think a driver really need to contact rider if he/she cannot find the rider in the real world. 
So do we need to add Rider in the Request?

**Comment by kgmills** [comment]
The request would likely have the user's fields for name, phone and email. Thus when it, as an object, is sent across ElasticSearch and picked up by Driver, it gets that info when it unpacks the object.
