### ISSUE TITLE
CentralController

### ISSUE THREAD

**Issue by kgmills** [CMPUT301F16T05/legendary-telegram#6]
If you noticed, we have a class called "CentralController". This class is the only Singleton in our project... something static to hold the dynamically changing user information (Requests, are they a rider or driver?) during a session. 

All other controllers (one for each activity) once they are done parsing the information of their activities, tell it to do something. 

In addition, it talks with the Gson and ESearch controllers as well as the User class.

**Comment by Cryosaurus** [comment]
Tweak can still be done but this has been technically done for a long time now
